CC=gcc
FLAGS=-Wall
MAIN=controlador.c
SOURCE=

compile :
	$(CC) $(FLAGS) -o controlador $(MAIN) $(SOURCE)

aux :
	$(CC) $(FLAGS) -o a.out auxiliar.c
	$(CC) $(FLAGS) -o b.out auxiliar.c
	$(CC) $(FLAGS) -o c.out auxiliar.c
